kbuild: fix missing -ldl
Projects built depending on soletta were broken
with errors like:
undefined reference to `dlopen'
when linking.

Signed-off-by: Bruno Dilly <bruno.dilly@intel.com>