Disable sanitizer on RIOT and Contiki
The toolchain need to provide libubsan or the build for this
OSes would fail due undefined reference to __ubsan_handle_type_mismatch(),
as for each board there is a different toolchain and most of they will not
provide this lib lets disable it.