Fix warning when XSI-compliant strerror_r is provided
On 64-bit systems, casting from int to pointers may cause warnings.

error: cast to 'char *' from smaller integer type 'int' [-Werror,-Wint-to-pointer-cast]

Signed-off-by: Thiago Macieira <thiago.macieira@intel.com>